version: 0.2

phases:
  pre_build:
    commands:
      - echo Iniciando sesión en Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 128055991296.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=128055991296.dkr.ecr.us-east-1.amazonaws.com/app-ecs-demo
      - IMAGE_TAG=latest

  build:
    commands:
      - echo Construyendo la imagen Docker...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Subiendo imagen a ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Generando imagedefinitions.json...
      - printf '[{"name":"app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
